global using FluentAssertions;
global using NSubstitute;
global using Principles.Constants;
global using Principles.Core;
global using Principles.Core.Extensions;
global using Principles.Core.Models;
global using Principles.Core.Services;
global using Principles.UnitTests.Infrastructure;
global using Xunit;
