using Google.Apis.Auth.OAuth2;
using Google.Apis.Auth.OAuth2.Flows;

namespace SET.Core.Services;

public class GoogleAuthService : IGoogleAuthService
{
    private readonly IConfiguration m_configuration;
    private readonly IRequestProvider m_requestProvider;
    private readonly ISettingsService m_settingsService;
    private readonly IUrlBuilder m_urlBuilder;

    public GoogleAuthService( IServiceProvider serviceProvider )
    {
        m_configuration = serviceProvider.GetRequiredService<IConfiguration>();
        m_requestProvider = serviceProvider.GetRequiredService<IRequestProvider>();
        m_settingsService = serviceProvider.GetRequiredService<ISettingsService>();
        m_urlBuilder = serviceProvider.GetRequiredService<IUrlBuilder>();
    }

    public async Task AuthorizeAsync()
    {
        string? clientId = null;
#if ANDROID
        clientId = m_configuration["Google:ClientIds:Android"];
#elif IOS
        clientId = m_configuration["Google:ClientIds:IOS"];
#endif

        if (string.IsNullOrEmpty( clientId ))
        {
            throw new InvalidOperationException( "Client secret is missing." );
        }

        string callbackUriAsStr = new LaunchUriBuilder( LaunchType.OAuth2Redirect ).Build().AbsoluteUri;
        Uri authUri;
        ClientSecrets clientSecrets = new()
        {
            ClientId = clientId
        };

        string[] requestedScopes = new[]
        {
            "https://www.googleapis.com/auth/userinfo.profile",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/user.gender.read"
        };

        GoogleAuthorizationCodeFlow codeFlow = new( new GoogleAuthorizationCodeFlow.Initializer
        {
            ClientSecrets = clientSecrets,
            Scopes = requestedScopes
        } );
        authUri = codeFlow.CreateAuthorizationCodeRequest( callbackUriAsStr ).Build();

        WebAuthenticatorResult authResult = await WebAuthenticator.Default.AuthenticateAsync(
            authUri,
            new Uri( callbackUriAsStr )
        ).DefaultConfigureAwait();

        authResult.Properties.TryGetValue("code", out string? code );
        authResult.Properties.TryGetValue("error", out string? error );

        if (!string.IsNullOrWhiteSpace( error ) || string.IsNullOrWhiteSpace(code))
        {
            if(string.IsNullOrWhiteSpace( code ))
            {
                error = "Code generated by Google to get tokens is null or white space";
            }

            throw new InvalidOperationException( error );
        }

        string tokenUrl = "https://oauth2.googleapis.com/token";
        var tokenRequestParams = new Dictionary<string, string>
        {
            { "code", code! },
            { "client_id", clientId },
            { "redirect_uri", callbackUriAsStr },
            { "grant_type", "authorization_code" }
        };

        GetGoogleTokenInfoResponse getGoogleTokenResponse = await m_requestProvider.PostAsync<Dictionary<string, string>, GetGoogleTokenInfoResponse>(
            tokenUrl,
            tokenRequestParams
        ).DefaultConfigureAwait();

        string url = m_urlBuilder.GoogleAuth;
        GoogleAuthRequest request = new()
        {
            AccessToken = getGoogleTokenResponse.AccessToken,
            IdToken = getGoogleTokenResponse.IdToken
        };
        GoogleAuthResponse response = await m_requestProvider.PostAsync<GoogleAuthRequest, GoogleAuthResponse>( url, request ).DefaultConfigureAwait();

        await m_settingsService.SetAuthAccessTokenAsync( response.Token ).DefaultConfigureAwait();
    }
}

