<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<Configurations>Debug;Release;LocalDebug</Configurations>
	</PropertyGroup>

	<PropertyGroup>
		<NullabilityInfoContextSupport>true</NullabilityInfoContextSupport>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.1" />
		<PackageReference Include="sqlite-net-sqlcipher" Version="1.9.172" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.11" />
		<PackageReference Include="Serilog" Version="3.1.1" />
		<PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='LocalDebug|AnyCPU'">
		<WarningLevel>4</WarningLevel>
		<NoWarn>1701;1702;CS1573;CS1591;CS8632</NoWarn>
		<DefineConstants>LOCALDEBUG;DEBUG;TRACE</DefineConstants>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Migrations\**\*.sql" />
	</ItemGroup>
</Project>
