<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<Configurations>Debug;Release;LocalDebug</Configurations>
	</PropertyGroup>

	<PropertyGroup>
		<NullabilityInfoContextSupport>true</NullabilityInfoContextSupport>
	</PropertyGroup>

	<PropertyGroup>
		<MtouchNoSymbolStrip Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">True</MtouchNoSymbolStrip>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='LocalDebug|net9.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
		<PackageReference Include="Plugin.LocalNotification" Version="11.1.4" />
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
		<PackageReference Include="Serilog" Version="3.1.1" />
		<PackageReference Include="Azure.AI.OpenAI" Version="1.0.0-beta.9" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.12" />
	</ItemGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='LocalDebug|AnyCPU'">
		<WarningLevel>4</WarningLevel>
		<NoWarn>1701;1702;CS1573;CS1591;CS8632</NoWarn>
		<DefineConstants>LOCALDEBUG;DEBUG;TRACE</DefineConstants>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>
</Project>
