CREATE TABLE IF NOT EXISTS ProgressOfHabit (
    LocalId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    LastModified TEXT NULL,
    Id INTEGER NULL,
    DateAsInt INTEGER NOT NULL,
    Value INTEGER NOT NULL,
    Notes TEXT NULL,
    UserHabitLocalId INTEGER NOT NULL,
        FOREIGN KEY (UserHabitLocalId) REFERENCES UserHabit (LocalId) ON DELETE CASCADE ON UPDATE CASCADE
);