//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SET.MAUI.Resources.AppStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SET.MAUI.Resources.AppStrings.LocStrings", typeof(LocStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add it anyway.
        /// </summary>
        internal static string AddItAnyway {
            get {
                return ResourceManager.GetString("AddItAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas of habit.
        /// </summary>
        internal static string AreasOfHabit {
            get {
                return ResourceManager.GetString("AreasOfHabit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic Habits.
        /// </summary>
        internal static string AtomicHabits {
            get {
                return ResourceManager.GetString("AtomicHabits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is impossible to parse.
        /// </summary>
        internal static string CannotParse {
            get {
                return ResourceManager.GetString("CannotParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is impossible to reload habits.
        /// </summary>
        internal static string CannotReloadHabits {
            get {
                return ResourceManager.GetString("CannotReloadHabits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        internal static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat With Helper.
        /// </summary>
        internal static string ChatWithHelper {
            get {
                return ResourceManager.GetString("ChatWithHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity can&apos;t be changed after creation of a habit.
        /// </summary>
        internal static string ComplexityHelpText {
            get {
                return ResourceManager.GetString("ComplexityHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity (1 - 10).
        /// </summary>
        internal static string ComplexityWithRange {
            get {
                return ResourceManager.GetString("ComplexityWithRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to load recommended habits based on your chosen areas, mission and main slogan?.
        /// </summary>
        internal static string ConfirmMessageOnRecommededHabitsView {
            get {
                return ResourceManager.GetString("ConfirmMessageOnRecommededHabitsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on selected areas, mission and slogan.
        /// </summary>
        internal static string ConfirmTitleOnRecommendedHabitsView {
            get {
                return ResourceManager.GetString("ConfirmTitleOnRecommendedHabitsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an email to app@principles.top.
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        internal static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        internal static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account?.
        /// </summary>
        internal static string DeleteAccountQuestion {
            get {
                return ResourceManager.GetString("DeleteAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete habit?.
        /// </summary>
        internal static string DeleteHabitQuestion {
            get {
                return ResourceManager.GetString("DeleteHabitQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the AI-lamp to get recommended habits..
        /// </summary>
        internal static string DescriptionOfAiLampTap {
            get {
                return ResourceManager.GetString("DescriptionOfAiLampTap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create this habit after you automate the others or create one that is less complex and less frequent (assuming you don&apos;t have too many processing habits). This will help you not to burn out and stick to your current habits..
        /// </summary>
        internal static string DescriptionOfCannotAddNewHabit {
            get {
                return ResourceManager.GetString("DescriptionOfCannotAddNewHabit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must have correct value.
        /// </summary>
        internal static string EmailMustHaveCorrectValue {
            get {
                return ResourceManager.GetString("EmailMustHaveCorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is incorrect..
        /// </summary>
        internal static string EmailOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("EmailOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text....
        /// </summary>
        internal static string EnterText {
            get {
                return ResourceManager.GetString("EnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        internal static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        internal static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every month.
        /// </summary>
        internal static string EveryMonth {
            get {
                return ResourceManager.GetString("EveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every week.
        /// </summary>
        internal static string EveryWeek {
            get {
                return ResourceManager.GetString("EveryWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every year.
        /// </summary>
        internal static string EveryYear {
            get {
                return ResourceManager.GetString("EveryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Name&quot;.
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Reason to follow&quot;.
        /// </summary>
        internal static string FieldReasonToFollow {
            get {
                return ResourceManager.GetString("FieldReasonToFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix the errors first.
        /// </summary>
        internal static string FixErrorsFirst {
            get {
                return ResourceManager.GetString("FixErrorsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        internal static string FridayShort {
            get {
                return ResourceManager.GetString("FridayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habit.
        /// </summary>
        internal static string Habit {
            get {
                return ResourceManager.GetString("Habit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any atomic habits yet.
        /// </summary>
        internal static string HabitCollectionIsEmptyDescription {
            get {
                return ResourceManager.GetString("HabitCollectionIsEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habits.
        /// </summary>
        internal static string Habits {
            get {
                return ResourceManager.GetString("Habits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helper.
        /// </summary>
        internal static string Helper {
            get {
                return ResourceManager.GetString("Helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helper SET.
        /// </summary>
        internal static string HelperName {
            get {
                return ResourceManager.GetString("HelperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I help you?.
        /// </summary>
        internal static string HowCanIHelpYou {
            get {
                return ResourceManager.GetString("HowCanIHelpYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to keep.
        /// </summary>
        internal static string HowToKeep {
            get {
                return ResourceManager.GetString("HowToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t want to wait, you can change the other fields for now.
        /// </summary>
        internal static string IfYouDontWantToWaitYouCanChangeOtherFields {
            get {
                return ResourceManager.GetString("IfYouDontWantToWaitYouCanChangeOtherFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect.
        /// </summary>
        internal static string Inspect {
            get {
                return ResourceManager.GetString("Inspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrally wise.
        /// </summary>
        internal static string IntegrallyWise {
            get {
                return ResourceManager.GetString("IntegrallyWise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a habit type that a person follows most of the time, but may make exceptions in special situations. For example, it may be the habit of telling the truth but being able to keep silent or deceive when it could cause serious harm to others..
        /// </summary>
        internal static string IntegrallyWiseHabitTypeShortDescription {
            get {
                return ResourceManager.GetString("IntegrallyWiseHabitTypeShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is max value.
        /// </summary>
        internal static string IsMaxValue {
            get {
                return ResourceManager.GetString("IsMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required.
        /// </summary>
        internal static string isRequired {
            get {
                return ResourceManager.GetString("isRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading content....
        /// </summary>
        internal static string LoadingContent {
            get {
                return ResourceManager.GetString("LoadingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking the &apos;Login&apos; button, you agree to:.
        /// </summary>
        internal static string LoginAgreementText {
            get {
                return ResourceManager.GetString("LoginAgreementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string LoginSignUpAgreementСonnectingText {
            get {
                return ResourceManager.GetString("LoginSignUpAgreementСonnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout?.
        /// </summary>
        internal static string LogoutQuestion {
            get {
                return ResourceManager.GetString("LogoutQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main slogan.
        /// </summary>
        internal static string MainSlogan {
            get {
                return ResourceManager.GetString("MainSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main slogan will be used to form better recommended habits. It helps you determine how to act when you don&apos;t want to do something or when you are faced with a challenge or temptation. For example, only Jesus..
        /// </summary>
        internal static string MainSloganExplanation {
            get {
                return ResourceManager.GetString("MainSloganExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        internal static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentality.
        /// </summary>
        internal static string Mentality {
            get {
                return ResourceManager.GetString("Mentality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor.
        /// </summary>
        internal static string Mentor {
            get {
                return ResourceManager.GetString("Mentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account will be permanently deleted. This action cannot be undone..
        /// </summary>
        internal static string MessageInDeleteAccountConfirm {
            get {
                return ResourceManager.GetString("MessageInDeleteAccountConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The habit will be permanently deleted. This action cannot be undone..
        /// </summary>
        internal static string MessageInDeleteHabitConfirm {
            get {
                return ResourceManager.GetString("MessageInDeleteHabitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to log out of your account?.
        /// </summary>
        internal static string MessageInLogoutConfirm {
            get {
                return ResourceManager.GetString("MessageInLogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        internal static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will be used to create more appropriate recommended habits for you. A mission is a life goal that keeps you motivated and helps you make the best choices in a variety of situations. For example, a mission might be to become the best and most moral entrepreneur in the world..
        /// </summary>
        internal static string MissionExplanation {
            get {
                return ResourceManager.GetString("MissionExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        internal static string MondayShort {
            get {
                return ResourceManager.GetString("MondayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open app to send an email. Maybe this program is not installed..
        /// </summary>
        internal static string MsgWhenCannotOpenAppToSendEmail {
            get {
                return ResourceManager.GetString("MsgWhenCannotOpenAppToSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Habits.
        /// </summary>
        internal static string MyHabits {
            get {
                return ResourceManager.GetString("MyHabits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection..
        /// </summary>
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes / How to keep habit.
        /// </summary>
        internal static string NotesOrHowToKeepHabit {
            get {
                return ResourceManager.GetString("NotesOrHowToKeepHabit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional).
        /// </summary>
        internal static string OptionalPlaceholder {
            get {
                return ResourceManager.GetString("OptionalPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Sex.
        /// </summary>
        internal static string OtherSex {
            get {
                return ResourceManager.GetString("OtherSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principles.
        /// </summary>
        internal static string Principles {
            get {
                return ResourceManager.GetString("Principles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     We may update our Privacy Policy from time to time. Thus, we advise you to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately, after they are posted on this page..
        /// </summary>
        internal static string PrivacyPolicyChangesText {
            get {
                return ResourceManager.GetString("PrivacyPolicyChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to This Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicyChangesTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Our Services do not address anyone under the age of 13. We do not knowingly collect personal identifiable information from children under 13. In the case we discover that a child under 13 has provided us with personal information, we will delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do necessary actions..
        /// </summary>
        internal static string PrivacyPolicyChildrensPrivacyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyChildrensPrivacyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s Privacy.
        /// </summary>
        internal static string PrivacyPolicyChildrensPrivacyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyChildrensPrivacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us on email: app@principles.top..
        /// </summary>
        internal static string PrivacyPolicyContactInfoText {
            get {
                return ResourceManager.GetString("PrivacyPolicyContactInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string PrivacyPolicyContactInfoTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyContactInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      For a better experience while using our Service, we may require you to provide us with certain personally identifiable information, including but not limited to your name and email address. The information that we collect will be used to contact and identify you. We retain this information until the User deletes account or violates the User Agreement or Privacy Policy..
        /// </summary>
        internal static string PrivacyPolicyInformationCollectionandUseText {
            get {
                return ResourceManager.GetString("PrivacyPolicyInformationCollectionandUseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Collection and Use.
        /// </summary>
        internal static string PrivacyPolicyInformationCollectionandUseTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyInformationCollectionandUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Principles operates cognominal app, which provides the SERVICE.
        ///    This page is used to inform visitors regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our Service, the Principles.
        ///    If you choose to use our Service, then you agree to the collection and use of information in relation with this policy. The Personal Information that we collect are used for providing and improving the Service. We will not use or share your information wit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivacyPolicyIntroduction {
            get {
                return ResourceManager.GetString("PrivacyPolicyIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Please be aware that each time you use our app, we automatically gather information sent by your device. This includes details such as your device’s Internet Protocol (IP) address, device&apos;s operating system version, device model, error details if it occurs, and other related data..
        /// </summary>
        internal static string PrivacyPolicyLogDataText {
            get {
                return ResourceManager.GetString("PrivacyPolicyLogDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Data.
        /// </summary>
        internal static string PrivacyPolicyLogDataTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyLogDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security..
        /// </summary>
        internal static string PrivacyPolicySecurityText {
            get {
                return ResourceManager.GetString("PrivacyPolicySecurityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string PrivacyPolicySecurityTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicySecurityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicyStrInLoginAndSignupViews {
            get {
                return ResourceManager.GetString("PrivacyPolicyStrInLoginAndSignupViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress of habits.
        /// </summary>
        internal static string ProgressOfHabits {
            get {
                return ResourceManager.GetString("ProgressOfHabits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question helps you to understand whether you have followed the habit on a particular day. For example, &quot;Did I do my best to exercise today, at least 15 minutes?&quot;.
        /// </summary>
        internal static string QuestionExplanation {
            get {
                return ResourceManager.GetString("QuestionExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason to follow.
        /// </summary>
        internal static string ReasonToFollow {
            get {
                return ResourceManager.GetString("ReasonToFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understanding why it is important to follow your habits helps you better determine how to act and improves your motivation to do something. It makes our actions consistent and reflects our character..
        /// </summary>
        internal static string ReasonToFollowExplanation {
            get {
                return ResourceManager.GetString("ReasonToFollowExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended habits by AI.
        /// </summary>
        internal static string RecommendedHabitsByAi {
            get {
                return ResourceManager.GetString("RecommendedHabitsByAi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended habits are loaded.
        /// </summary>
        internal static string RecommendedHabitsSuccessfullyLoaded {
            get {
                return ResourceManager.GetString("RecommendedHabitsSuccessfullyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        internal static string Relationships {
            get {
                return ResourceManager.GetString("Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Required.
        /// </summary>
        internal static string RequiredErrorText {
            get {
                return ResourceManager.GetString("RequiredErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Required.
        /// </summary>
        internal static string RequiredHelpText {
            get {
                return ResourceManager.GetString("RequiredHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string SaturdayShort {
            get {
                return ResourceManager.GetString("SaturdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a self-development assistant. You can ask me different questions. For example, &quot;What is an atomic habit?&quot;.
        /// </summary>
        internal static string SelfDevelopmentAssistantShortDescription {
            get {
                return ResourceManager.GetString("SelfDevelopmentAssistantShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the priorities with drag and drop.
        /// </summary>
        internal static string SetPriorityByDragAndDrop {
            get {
                return ResourceManager.GetString("SetPriorityByDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing up.
        /// </summary>
        internal static string SigningUp {
            get {
                return ResourceManager.GetString("SigningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking the &apos;Signing Up&apos; button, you agree to:.
        /// </summary>
        internal static string SignUpAgreementText {
            get {
                return ResourceManager.GetString("SignUpAgreementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sociality.
        /// </summary>
        internal static string Sociality {
            get {
                return ResourceManager.GetString("Sociality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirituality.
        /// </summary>
        internal static string Spirituality {
            get {
                return ResourceManager.GetString("Spirituality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason to follow.
        /// </summary>
        internal static string StrongReasonToFollow {
            get {
                return ResourceManager.GetString("StrongReasonToFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string SundayShort {
            get {
                return ResourceManager.GetString("SundayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tab &quot;Data&quot;.
        /// </summary>
        internal static string TabData {
            get {
                return ResourceManager.GetString("TabData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tab &quot;How to keep&quot;.
        /// </summary>
        internal static string TabHowToKeep {
            get {
                return ResourceManager.GetString("TabHowToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string ThursdayShort {
            get {
                return ResourceManager.GetString("ThursdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times per.
        /// </summary>
        internal static string timesPer {
            get {
                return ResourceManager.GetString("timesPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding this habit will hurt you.
        /// </summary>
        internal static string TitleOfCannotAddNewHabit {
            get {
                return ResourceManager.GetString("TitleOfCannotAddNewHabit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To integer.
        /// </summary>
        internal static string ToInteger {
            get {
                return ResourceManager.GetString("ToInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have sent the maximum number of messages in one chat.
        /// </summary>
        internal static string TooManyMessagesError {
            get {
                return ResourceManager.GetString("TooManyMessagesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        internal static string TuesdayShort {
            get {
                return ResourceManager.GetString("TuesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User agreement.
        /// </summary>
        internal static string UserAgreement {
            get {
                return ResourceManager.GetString("UserAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      1.1. Your use of the App constitutes your agreement to all the terms of this Agreement. If you do not agree to these terms, please do not use the App..
        /// </summary>
        internal static string UserAgreementAcceptanceofTermsText {
            get {
                return ResourceManager.GetString("UserAgreementAcceptanceofTermsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Acceptance of Terms.
        /// </summary>
        internal static string UserAgreementAcceptanceofTermsTitle {
            get {
                return ResourceManager.GetString("UserAgreementAcceptanceofTermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      If you have any questions about this Agreement, please contact me: app@principles.top..
        /// </summary>
        internal static string UserAgreementContactInformation {
            get {
                return ResourceManager.GetString("UserAgreementContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      5.1. The App is provided on an &quot;as is&quot; and &quot;as available&quot; basis without any warranties of any kind, express or implied.
        ///     5.2. Principles does not warrant that the App will be uninterrupted, error-free, or free of viruses or other harmful components..
        /// </summary>
        internal static string UserAgreementDisclaimerofWarrantiesText {
            get {
                return ResourceManager.GetString("UserAgreementDisclaimerofWarrantiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Disclaimer of Warranties.
        /// </summary>
        internal static string UserAgreementDisclaimerofWarrantiesTitle {
            get {
                return ResourceManager.GetString("UserAgreementDisclaimerofWarrantiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      4.1. The App and all of its content, including but not limited to text, graphics, logos, icons, images, and software, are the property of Principles or its licensors and are protected by copyright laws.
        ///     4.2. Content provided by Principles is protected and cannot be reproduced, processed, distributed, framed, published, downloaded, transmitted, sold, or used in any form, in whole or in part, without the prior written consent of Principles. Unauthorized reproduction, copying, collection, systematiza [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserAgreementIntellectualPropertyText {
            get {
                return ResourceManager.GetString("UserAgreementIntellectualPropertyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Intellectual Property.
        /// </summary>
        internal static string UserAgreementIntellectualPropertyTitle {
            get {
                return ResourceManager.GetString("UserAgreementIntellectualPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      This User Agreement (hereinafter referred to as the &quot;Agreement&quot;) is entered into between you (hereinafter referred to as &quot;You&quot;) and an individual entrepreneur Bats Bogdan (hereinafter referred to as &quot;I&quot;, &quot;me&quot;, &quot;Principles&quot;) the owner and operator of the Application named Principles (hereinafter referred to as the &quot;App&quot;). Please carefully read this Agreement before using the App..
        /// </summary>
        internal static string UserAgreementIntroduction {
            get {
                return ResourceManager.GetString("UserAgreementIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated: 29.05.2024..
        /// </summary>
        internal static string UserAgreementLastUpdate {
            get {
                return ResourceManager.GetString("UserAgreementLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      7.1. Under this Agreement, Principles grants the User a simple (non-exclusive) license to use the App. This license is non-transferable and may be revoked at any time.
        ///     7.2. The license for the App remains valid indefinitely unless otherwise agreed upon in writing by the parties..
        /// </summary>
        internal static string UserAgreementLicenseText {
            get {
                return ResourceManager.GetString("UserAgreementLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. License.
        /// </summary>
        internal static string UserAgreementLicenseTitle {
            get {
                return ResourceManager.GetString("UserAgreementLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      6.1. In no event shall Principles be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of the App.
        ///     6.2. Principles&apos; total liability to you for all claims arising out of or in connection with this Agreement shall not exceed the amount paid by you, if any, for accessing the App..
        /// </summary>
        internal static string UserAgreementLimitationofLiabilityText {
            get {
                return ResourceManager.GetString("UserAgreementLimitationofLiabilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Limitation of Liability.
        /// </summary>
        internal static string UserAgreementLimitationofLiabilityTitle {
            get {
                return ResourceManager.GetString("UserAgreementLimitationofLiabilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      8.1. The processing of the User&apos;s personal data is carried out in accordance with the legislation of the Ukraine and the Privacy Policy..
        /// </summary>
        internal static string UserAgreementPersonalDataText {
            get {
                return ResourceManager.GetString("UserAgreementPersonalDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Personal data.
        /// </summary>
        internal static string UserAgreementPersonalDataTitle {
            get {
                return ResourceManager.GetString("UserAgreementPersonalDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      3.1. I reserve the right to make changes to the terms of this Agreement at any time. Any modifications will be effective immediately upon posting on the App. Your continued use of the App after such changes will constitute your acknowledgment and acceptance of the modified terms.
        ///     3.2. I reserve the right to suspend or terminate your access to the App at any time for any reason, including but not limited to violation of this Agreement or misuse of the App..
        /// </summary>
        internal static string UserAgreementRightsandResponsibilitiesofPrinciplesText {
            get {
                return ResourceManager.GetString("UserAgreementRightsandResponsibilitiesofPrinciplesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Rights and Responsibilities of Principles.
        /// </summary>
        internal static string UserAgreementRightsandResponsibilitiesofPrinciplesTitle {
            get {
                return ResourceManager.GetString("UserAgreementRightsandResponsibilitiesofPrinciplesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      2.1. You agree not to violate any copyrights, property rights, or other rights of any party associated with the use of the App.
        ///     2.2. You are solely responsible for any information you provide through the App, including your comments, feedback, and any content.
        ///     2.3. You agree not to use the App for any illegal or abusive purposes..
        /// </summary>
        internal static string UserAgreementRightsandResponsibilitiesOfUserText {
            get {
                return ResourceManager.GetString("UserAgreementRightsandResponsibilitiesOfUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Rights and Responsibilities of the User.
        /// </summary>
        internal static string UserAgreementRightsandResponsibilitiesOfUserTitle {
            get {
                return ResourceManager.GetString("UserAgreementRightsandResponsibilitiesOfUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      If any provision of this Agreement is found to be invalid or unenforceable, such provision shall be severed from the Agreement, and the remaining provisions shall remain in full force and effect.
        ///By using the App, you acknowledge that you have read, understood, and agree to be bound by the terms of this Agreement..
        /// </summary>
        internal static string UserAgreementSeverabilityText {
            get {
                return ResourceManager.GetString("UserAgreementSeverabilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severability.
        /// </summary>
        internal static string UserAgreementSeverabilityTitle {
            get {
                return ResourceManager.GetString("UserAgreementSeverabilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agreement.
        /// </summary>
        internal static string UserAgreementStrInLoginAndSignupViews {
            get {
                return ResourceManager.GetString("UserAgreementStrInLoginAndSignupViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use subhabits.
        /// </summary>
        internal static string UseSubhabits {
            get {
                return ResourceManager.GetString("UseSubhabits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision.
        /// </summary>
        internal static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        internal static string Visual {
            get {
                return ResourceManager.GetString("Visual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization.
        /// </summary>
        internal static string Visualization {
            get {
                return ResourceManager.GetString("Visualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        internal static string WednesdayShort {
            get {
                return ResourceManager.GetString("WednesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without exceptions.
        /// </summary>
        internal static string WithoutExceptions {
            get {
                return ResourceManager.GetString("WithoutExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a habit type that a person adheres to strictly and never makes exceptions, even in emergency situations. For example, refusal to drink alcohol or tobacco, regardless of the circumstances..
        /// </summary>
        internal static string WithoutExceptionsHabitTypeShortDescription {
            get {
                return ResourceManager.GetString("WithoutExceptionsHabitTypeShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman.
        /// </summary>
        internal static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized..
        /// </summary>
        internal static string YouAreNotAuthorized {
            get {
                return ResourceManager.GetString("YouAreNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Main Slogan.
        /// </summary>
        internal static string YourMainSlogan {
            get {
                return ResourceManager.GetString("YourMainSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your main slogan successfully saved.
        /// </summary>
        internal static string YourMainSloganSuccessfullySaved {
            get {
                return ResourceManager.GetString("YourMainSloganSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Mission.
        /// </summary>
        internal static string YourMission {
            get {
                return ResourceManager.GetString("YourMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mission successfully saved.
        /// </summary>
        internal static string YourMissionSuccessfullySaved {
            get {
                return ResourceManager.GetString("YourMissionSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        internal static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name successfully saved.
        /// </summary>
        internal static string YourNameSuccessfullySaved {
            get {
                return ResourceManager.GetString("YourNameSuccessfullySaved", resourceCulture);
            }
        }
    }
}
