using System.Security.Cryptography;
using System.Text;

namespace Principles.Core.Services;

public class GoogleAuthService : IGoogleAuthService
{
    private readonly IConfiguration m_configuration;
    private readonly IRequestProvider m_requestProvider;
    private readonly ISettingsService m_settingsService;
    private readonly IUrlBuilder m_urlBuilder;
    private readonly IUserService m_userService;

    public GoogleAuthService( IServiceProvider serviceProvider )
    {
        m_configuration = serviceProvider.GetRequiredService<IConfiguration>();
        m_requestProvider = serviceProvider.GetRequiredService<IRequestProvider>();
        m_settingsService = serviceProvider.GetRequiredService<ISettingsService>();
        m_urlBuilder = serviceProvider.GetRequiredService<IUrlBuilder>();
        m_userService = serviceProvider.GetRequiredService<IUserService>();
    }

    public async Task AuthorizeAsync()
    {
        string? clientId = null;
#if ANDROID
        clientId = m_configuration["Google:ClientIds:Android"];
#elif IOS
        clientId = m_configuration["Google:ClientIds:IOS"];
#endif

        if (string.IsNullOrEmpty( clientId ))
        {
            throw new InvalidOperationException( "Client secret is missing." );
        }

        string codeVerifier = CodeVerifier();
        string codeChallenge = CodeChallenge( codeVerifier );

        string callbackUriAsStr = new LaunchUriBuilder( LaunchType.OAuth2Redirect ).Build().AbsoluteUri;

        StringBuilder authUrlBuider = new( value: "https://accounts.google.com/o/oauth2/v2/auth" );
        authUrlBuider.Append( "?access_type=offline" );
        authUrlBuider.Append( "&response_type=code" );
        authUrlBuider.Append( $"&client_id={clientId}" );
        authUrlBuider.Append( $"&redirect_uri={callbackUriAsStr}" );
        authUrlBuider.Append( "&scope=openid%20profile%20email%20https://www.googleapis.com/auth/user.gender.read" );
        authUrlBuider.Append( "&code_challenge_method=S256" );
        authUrlBuider.Append( $"&code_challenge={codeChallenge}" );
        authUrlBuider.Append( "&service=lso" );
        authUrlBuider.Append( "&o2v=2" );
        authUrlBuider.Append( "&ddm=0" );
        authUrlBuider.Append( "&flowName=GeneralOAuthFlow" );

        string authUriStr = authUrlBuider.ToString();
        Uri authUri = new( authUriStr );

        WebAuthenticatorResult authResult = await WebAuthenticator.Default.AuthenticateAsync(
            authUri,
            new Uri( callbackUriAsStr )
        ).DefaultConfigureAwait();

        authResult.Properties.TryGetValue("code", out string? code );
        authResult.Properties.TryGetValue("error", out string? error );

        if (!string.IsNullOrWhiteSpace( error ) || string.IsNullOrWhiteSpace(code))
        {
            if(string.IsNullOrWhiteSpace( code ) && string.IsNullOrWhiteSpace( error ))
            {
                error = $"Code generated by Google to get tokens is null or white space";
            }

            throw new InvalidOperationException( error );
        }

        string tokenUrl = "https://oauth2.googleapis.com/token";
        var tokenRequestParams = new Dictionary<string, string>
        {
            { "code", code! },
            { "client_id", clientId },
            { "redirect_uri", callbackUriAsStr },
            { "grant_type", "authorization_code" },
            { "code_verifier", codeVerifier }
        };

        GetGoogleTokenInfoResponse getGoogleTokenResponse = await m_requestProvider.PostAsync<Dictionary<string, string>, GetGoogleTokenInfoResponse>(
            tokenUrl,
            tokenRequestParams
        ).DefaultConfigureAwait();

        string url = m_urlBuilder.GoogleAuth;
        GoogleAuthRequest request = new()
        {
            AccessToken = getGoogleTokenResponse.AccessToken,
            IdToken = getGoogleTokenResponse.IdToken
        };
        GoogleAuthResponse response = await m_requestProvider.PostAsync<GoogleAuthRequest, GoogleAuthResponse>( url, request ).DefaultConfigureAwait();

        await m_userService.ClearLocalDataAsync().ConfigureAwait( false );
        await m_settingsService.SetAuthAccessTokenAsync( response.Token ).DefaultConfigureAwait();
    }

    private string CodeVerifier()
    {
        byte[] randomBytes = RandomNumberGenerator.GetBytes( count: 32 );
        string result = Base64UrlEncode( randomBytes );
        return result;
    }

    private string Base64UrlEncode( byte[] input )
    {
        string result = Convert.ToBase64String( input );
        result = result.Replace( "+", "-" ).Replace( "/", "_" ).Replace( "=", "" );
        return result;
    }

    private string CodeChallenge( string codeVerifier )
    {
        using var sha256 = SHA256.Create();
        byte[] hash = sha256.ComputeHash( Encoding.ASCII.GetBytes( codeVerifier ) );
        string result = Base64UrlEncode( hash );
        return result;
    }
}
