<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>
        
		<OutputType>Exe</OutputType>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Principles</RootNamespace>
		<NeutralLanguage>en</NeutralLanguage>
		<Nullable>enable</Nullable>

		<!-- App Identifier -->
		<ApplicationId>com.set.principles</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>2.1.5</ApplicationDisplayVersion>
		<ApplicationVersion>42</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net9.0-android'">21.0</SupportedOSPlatformVersion>
		<ApplicationTitle>Principles</ApplicationTitle>
		<Configurations>Debug;Release;LocalDebug</Configurations>
	</PropertyGroup>

	<PropertyGroup>
		<NullabilityInfoContextSupport>true</NullabilityInfoContextSupport>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
	  <NoWarn>1701;1702;8632</NoWarn>
	  <ArchiveOnBuild>true</ArchiveOnBuild>
	  <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
	  <CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
	  <CodesignKey>iPhone Distribution: Bohdan Bats (CHVN5SL89P)</CodesignKey>
	  <CodesignProvision>PRINCIPLES</CodesignProvision>
	  <CreatePackage>false</CreatePackage>
	  <BuildIpa>true</BuildIpa>
	</PropertyGroup>
	
	<!-- App Icon -->
	<ItemGroup Condition="$(TargetFramework.Contains('-android'))">
		<MauiIcon Include="Resources\AppIcon\appicon.png" Color="#1F1F1F" ForegroundScale="0.6" />
    </ItemGroup>
	<ItemGroup Condition="$(TargetFramework.Contains('-ios'))">
        <MauiIcon Include="Resources\AppIcon\appicon.png" Color="#1F1F1F" />
    </ItemGroup>

	<ItemGroup>
		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\appicon.png" Color="#1F1F1F" BaseSize="320,320" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*svg" BaseSize="23, 23" />
		<MauiImage Include="Resources\Images\*png" BaseSize="23, 23" />
		<MauiImage Update="Resources\Images\settings.svg" BaseSize="40, 40" />
		<MauiImage Update="Resources\Images\plus.svg" BaseSize="40, 40" />
		<MauiImage Update="Resources\Images\reminder_first.svg" BaseSize="40, 40" />
		<MauiImage Update="Resources\Images\reminder_second.svg" BaseSize="60, 60" />
		<MauiImage Update="Resources\Images\reminder_third.svg" BaseSize="40, 40" />
		<MauiImage Update="Resources\Images\edit.png" BaseSize="40, 40" />
		<MauiImage Update="Resources\Images\delete.png" BaseSize="40, 40" />
		<MauiImage Update="Resources\Images\logolargesize.png" BaseSize="200, 200" />
		<MauiImage Update="Resources\Images\larger_help.png" BaseSize="40, 40" />
		<MauiImage Include="Resources\Images\*jpg" BaseSize="23, 23" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />
		
		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup Condition="$(TargetFramework.Contains('-ios'))">
      <BundleResource Include="Platforms\iOS\Resources\**" TargetPath="%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
      <IPhoneResourcePrefix>Platforms/iOS/Resources/loc</IPhoneResourcePrefix>
    </PropertyGroup>

	<ItemGroup>
	  <None Remove="appsettings.Development.json" />
	  <None Remove="Platforms\Android\Resources\values-ru\colors.xml" />
	  <None Remove="Platforms\Android\Resources\values-ru\Strings.xml" />
	  <None Remove="Platforms\Android\Resources\values-ru\styles.xml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="9.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
		<PackageReference Include="Plugin.LocalNotification" Version="11.1.4" />
		<PackageReference Include="Serilog" Version="3.1.1" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
		<PackageReference Include="Serilog.Sinks.Xamarin" Version="1.0.0" />
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.12" />
		<PackageReference Include="CommunityToolkit.Maui.Markup" Version="4.0.0" />
		<PackageReference Include="Polly.Extensions" Version="8.4.0" />
		<PackageReference Include="SkiaSharp.Extended.UI.Maui" Version="2.0.0" />
		<PackageReference Include="DevExpress.Maui.CollectionView" Version="24.2.3" />
		<PackageReference Include="DevExpress.Maui.Controls" Version="24.2.3" />
		<PackageReference Include="DevExpress.Maui.DataGrid" Version="24.2.3" />
		<PackageReference Include="DevExpress.Maui.Editors" Version="24.2.3" />
		<PackageReference Include="Azure.AI.OpenAI" Version="1.0.0-beta.9" />
		<PackageReference Include="System.Private.Uri" Version="4.3.2" />
		<PackageReference Include="System.Text.Json" Version="8.0.5" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="App.xaml.cs">
		  <DependentUpon>App.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\StartupView.xaml.cs">
		  <DependentUpon>StartupView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\ForgetPasswordView.xaml.cs">
		  <DependentUpon>ForgetPasswordView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\EditPrincipleView.xaml.cs">
		  <DependentUpon>EditPrincipleView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SettingsView.xaml.cs">
		  <DependentUpon>SettingsView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\LoginView.xaml.cs">
		  <DependentUpon>LoginView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\MentorView.xaml.cs">
		  <DependentUpon>MentorView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\PrinciplesView.xaml.cs">
		  <DependentUpon>PrinciplesView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\ProfileView.xaml.cs">
		  <DependentUpon>ProfileView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SignupView.xaml.cs">
		  <DependentUpon>SignupView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Templates\DefaultActivityIndicator.xaml.cs">
		  <DependentUpon>DefaultActivityIndicator.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Templates\BaseTemplateView.xaml.cs">
		  <DependentUpon>BaseTemplateView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Platforms\iOS\LocStrings.Designer.cs">
		  <ExcludeFromCurrentConfiguration>true</ExcludeFromCurrentConfiguration>
		  <DependentUpon>LocStrings.resx</DependentUpon>
		</Compile>
		<Compile Update="Resources\AppStrings\LocStrings.Designer.cs">
		  <DependentUpon>LocStrings.resx</DependentUpon>
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		</Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="App.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppShell.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CircularProgressBar.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\StartupView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ForgetPasswordView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\EditPrincipleView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SettingsView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MentorView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\PrinciplesView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ProfileView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SignupView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Templates\DefaultActivityIndicator.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Templates\BaseTemplateView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\UpdatePopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Condition=" '$(EnableDefaultEmbeddedResourceItems)' == 'true' " Update="Resources\AppStrings\LocStrings.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>LocStrings.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
	  <BundleResource Include="Platforms\iOS\Resources\loc\en.lproj\InfoPlist.strings" />
	  <BundleResource Include="Platforms\iOS\Resources\loc\uk.lproj\InfoPlist.strings" />
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Include="appsettings.Development.json">
	    <DependentUpon>appsettings.json</DependentUpon>
	  </EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Principles.Core\Principles.Core.csproj" />
	</ItemGroup>
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
		<BundleResource Include="Platforms\iOS\PrivacyInfo.xcprivacy" LogicalName="PrivacyInfo.xcprivacy" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="appsettings.json" />
	</ItemGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
      <WarningLevel>4</WarningLevel>
      <NoWarn>1701;1702;CS1573;CS1591;CS8632</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='LocalDebug|AnyCPU'">
      <WarningLevel>4</WarningLevel>
      <NoWarn>1701;1702;CS1573;CS1591;CS8632</NoWarn>
      <DefineConstants>LOCALDEBUG;DEBUG;TRACE</DefineConstants>
      <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>
</Project>
